spring:
  datasource:
    url: jdbc:mysql://localhost:3306/NEWS
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678


  jpa:
    hibernate:
      ddl-auto: create                         # 테이블 자동 생성 (create, update, none)
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect  # Hibernate dialect 설정
    show-sql: true                             # SQL 쿼리 출력 여부
    database-platform: org.hibernate.dialect.MySQL8Dialect

  config:
    import: application-secret.yml




